site_name: Phase Portrait

nav:
- Home:
  - Overview: index.md
  - License: license.md
  - Installation: installation.md

- Tutorials:
  - '2D phase portraits' : 'reference/legacy/phaseportrait2d_examples.md'
  - '2D & 3D trajectories' : 'reference/legacy/trajectories_examples.md'
  - '1D maps and cobweb plots' : 'reference/legacy/mapsandcobweb_examples.md'

- Code Reference: reference/

- Legacy docs:
  - "Cobweb plots" : "reference/legacy/cobweb.md"
  - "dF functions" : "reference/legacy/dFfunction.md"
  - "Generator" : "reference/legacy/generator.md"
  - "Map" : "reference/legacy/map.md"
  - "Map 1D" : "reference/legacy/map1d.md"
  - "Nullclines" : "reference/legacy/nullclines.md"
  - "Phase portrait 2D" : "reference/legacy/phaseportrait2d.md"
  - "Phase portrait 3D" : "reference/legacy/phaseportrait3d.md"
  - "Runge Kutta" : "reference/legacy/rungekutta.md"
  - "Sliders" : "reference/legacy/slider.md"
  - "Stream lines generic" : "reference/legacy/streamlines_base.md"
  - "Trajectory generic" : "reference/legacy/trajectory.md"
  - "Trajectory 2D" : "reference/legacy/trajectory2d.md"
  - "Trajectory 3D" : "reference/legacy/trajectory3d.md"

# theme: readthedocs
theme:
    name: "material"
    logo: img/duckduck.png
    favicon: img/favicon.ico

    palette:
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: light)"
      scheme: slate
      primary: orange
      accent: light-green
      toggle:
        icon: material/brightness-7
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: dark)"
      scheme: default
      primary: orange
      accent: light-green
      toggle:
        icon: material/brightness-3 
        name: Switch to dark mode

    features:
      - content.code.annotate
      - content.code.copy
      - navigation.tabs
      - navigation.tracking
      - navigation.instant

repo_url: https://github.com/phaseportrait/phaseportrait/
site_description: Python package for visualizing non-linear dynamics and chaos
site_author : Víctor Loras & Unai Lería
copyright : Copyright © 2024 Víctor Loras, Unai Lería
site_url : https://phaseportrait.github.io/

watch: [README.md, phaseportrait, examples]

plugins:
- search
- autorefs
- gen-files:
    scripts:
      - docs/generate_reference_docs.py
- literate-nav:
    nav_file: reference/SUMMARY.md
- mkdocstrings:
    custom_templates: templates
    default_handler: python
    handlers:
      python:
        options:
          show_source: true
